name: ada_bread
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=2.7.0 <3.0.0'}
dependencies:
  flutter: {sdk: flutter}
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.2
  convex_bottom_bar: ^3.1.0+1
  percent_indicator: ^3.4.0
  intl: ^0.17.0
  path_provider: ^2.0.8
  syncfusion_flutter_pdf: ^19.4.47-beta
  open_file: ^3.2.1
  provider: ^6.0.3
  flutter_image_slideshow: any
  flutter_animation_progress_bar: ^2.0.1
  http: ^0.13.4
  flutter_slidable: ^1.2.0
  url_launcher: ^6.0.18
  sqlbrite: ^2.2.0
  sqflite: null
  charcode: ^1.3.1
  lite_rolling_switch: ^0.1.1
  font_awesome_flutter: ^9.2.0
  grouped_list: ^4.2.0
  slimy_card: ^1.0.4
  fab_circular_menu: ^1.0.2
  flutter_staggered_animations: ^1.0.0
  fancy_shimmer_image: ^2.0.2
  syncfusion_flutter_sliders: null
  flutter_spinkit: ^5.1.0
  material_design_icons_flutter: 5.0.6996
  page_transition: ^2.0.4
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  firebase_storage: ^10.2.4
  cached_network_image: ^3.0.0
  image_picker: ^0.8.1+3
  flutter_local_notifications: null
  overlay_support: ^1.2.1
  image_cropper: ^1.4.1
  uuid: 3.0.6
  firebase_messaging: null
  firebase_analytics: ^9.3.8
  webview_flutter: ^3.0.4
  flutter_bloc: ^8.1.1
dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets: [images/]
  fonts: []
